services:
  app:
    # build:
    #   context: .
    #   dockerfile: Dockerfile.dind
    image: whatwewant/gzcaas:v1-dind
    ports:
      - 0.0.0.0:8838:8838
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: []
    environment:
      #
      CAAS_SERVER_URL: http://10.208.203.172:8080
      CAAS_CLIENT_ID: 48540daa2a8eeca6188be94b
      CAAS_CLIENT_SECRET: 4a0a35b0dc2a17c8310758b66bcd7257
    privileged: true
    
